# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'piano_another.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Piano(object):
    def setupUi(self, Piano):
        Piano.setObjectName("Piano")
        Piano.resize(581, 194)
        self.gridLayout_2 = QtWidgets.QGridLayout(Piano)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.d_btn = QtWidgets.QPushButton(Piano)
        self.d_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.d_btn.setObjectName("d_btn")
        self.gridLayout.addWidget(self.d_btn, 0, 0, 1, 1)
        self.sol_btn = QtWidgets.QPushButton(Piano)
        self.sol_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.sol_btn.setObjectName("sol_btn")
        self.gridLayout.addWidget(self.sol_btn, 0, 4, 1, 1)
        self.re_btn = QtWidgets.QPushButton(Piano)
        self.re_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.re_btn.setObjectName("re_btn")
        self.gridLayout.addWidget(self.re_btn, 0, 1, 1, 1)
        self.mi_btn = QtWidgets.QPushButton(Piano)
        self.mi_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.mi_btn.setObjectName("mi_btn")
        self.gridLayout.addWidget(self.mi_btn, 0, 2, 1, 1)
        self.la_btn = QtWidgets.QPushButton(Piano)
        self.la_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.la_btn.setObjectName("la_btn")
        self.gridLayout.addWidget(self.la_btn, 0, 5, 1, 1)
        self.si_btn = QtWidgets.QPushButton(Piano)
        self.si_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.si_btn.setObjectName("si_btn")
        self.gridLayout.addWidget(self.si_btn, 0, 6, 1, 1)
        self.fa_btn = QtWidgets.QPushButton(Piano)
        self.fa_btn.setMinimumSize(QtCore.QSize(0, 60))
        self.fa_btn.setObjectName("fa_btn")
        self.gridLayout.addWidget(self.fa_btn, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Piano)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.back_btn = QtWidgets.QPushButton(self.groupBox)
        self.back_btn.setGeometry(QtCore.QRect(0, 0, 71, 61))
        self.back_btn.setObjectName("back_btn")
        self.piano_settings_btn = QtWidgets.QPushButton(self.groupBox)
        self.piano_settings_btn.setGeometry(QtCore.QRect(80, 0, 71, 61))
        self.piano_settings_btn.setObjectName("piano_settings_btn")
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Piano)
        QtCore.QMetaObject.connectSlotsByName(Piano)

    def retranslateUi(self, Piano):
        _translate = QtCore.QCoreApplication.translate
        Piano.setWindowTitle(_translate("Piano", "Dialog"))
        self.d_btn.setText(_translate("Piano", "C"))
        self.sol_btn.setText(_translate("Piano", "G"))
        self.re_btn.setText(_translate("Piano", "D"))
        self.mi_btn.setText(_translate("Piano", "E"))
        self.la_btn.setText(_translate("Piano", "A"))
        self.si_btn.setText(_translate("Piano", "H"))
        self.fa_btn.setText(_translate("Piano", "F"))
        self.back_btn.setText(_translate("Piano", "BACK"))
        self.piano_settings_btn.setText(_translate("Piano", "SETTINGS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Piano = QtWidgets.QDialog()
    ui = Ui_Piano()
    ui.setupUi(Piano)
    Piano.show()
    sys.exit(app.exec_())
