# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swap_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SwapTool(object):
    def setupUi(self, SwapTool):
        SwapTool.setObjectName("SwapTool")
        SwapTool.resize(400, 250)
        SwapTool.setMinimumSize(QtCore.QSize(400, 250))
        SwapTool.setMaximumSize(QtCore.QSize(400, 250))
        self.label_current_tool = QtWidgets.QLabel(SwapTool)
        self.label_current_tool.setGeometry(QtCore.QRect(20, 200, 81, 20))
        self.label_current_tool.setObjectName("label_current_tool")
        self.label_tool = QtWidgets.QLabel(SwapTool)
        self.label_tool.setGeometry(QtCore.QRect(120, 200, 91, 21))
        self.label_tool.setObjectName("label_tool")
        self.back_to_settings_btn = QtWidgets.QPushButton(SwapTool)
        self.back_to_settings_btn.setEnabled(True)
        self.back_to_settings_btn.setGeometry(QtCore.QRect(10, 10, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_to_settings_btn.sizePolicy().hasHeightForWidth())
        self.back_to_settings_btn.setSizePolicy(sizePolicy)
        self.back_to_settings_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.back_to_settings_btn.setSizeIncrement(QtCore.QSize(0, 0))
        self.back_to_settings_btn.setObjectName("back_to_settings_btn")
        self.widget = QtWidgets.QWidget(SwapTool)
        self.widget.setGeometry(QtCore.QRect(92, 9, 301, 170))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.piano_swap_btn = QtWidgets.QPushButton(self.widget)
        self.piano_swap_btn.setObjectName("piano_swap_btn")
        self.verticalLayout.addWidget(self.piano_swap_btn)
        self.guitar_swap_btn = QtWidgets.QPushButton(self.widget)
        self.guitar_swap_btn.setObjectName("guitar_swap_btn")
        self.verticalLayout.addWidget(self.guitar_swap_btn)
        self.clarinet_swap_btn = QtWidgets.QPushButton(self.widget)
        self.clarinet_swap_btn.setObjectName("clarinet_swap_btn")
        self.verticalLayout.addWidget(self.clarinet_swap_btn)
        self.violin_swap_btn = QtWidgets.QPushButton(self.widget)
        self.violin_swap_btn.setObjectName("violin_swap_btn")
        self.verticalLayout.addWidget(self.violin_swap_btn)
        self.saxophone_swap_btn = QtWidgets.QPushButton(self.widget)
        self.saxophone_swap_btn.setObjectName("saxophone_swap_btn")
        self.verticalLayout.addWidget(self.saxophone_swap_btn)
        self.trombone_swap_btn = QtWidgets.QPushButton(self.widget)
        self.trombone_swap_btn.setObjectName("trombone_swap_btn")
        self.verticalLayout.addWidget(self.trombone_swap_btn)

        self.retranslateUi(SwapTool)
        QtCore.QMetaObject.connectSlotsByName(SwapTool)

    def retranslateUi(self, SwapTool):
        _translate = QtCore.QCoreApplication.translate
        SwapTool.setWindowTitle(_translate("SwapTool", "Dialog"))
        self.label_current_tool.setText(_translate("SwapTool", "CURRENT TOOL:"))
        self.label_tool.setText(_translate("SwapTool", "PIANO"))
        self.back_to_settings_btn.setText(_translate("SwapTool", "BACK"))
        self.piano_swap_btn.setText(_translate("SwapTool", "PIANO"))
        self.guitar_swap_btn.setText(_translate("SwapTool", "GUITAR"))
        self.clarinet_swap_btn.setText(_translate("SwapTool", "CLARINET"))
        self.violin_swap_btn.setText(_translate("SwapTool", "VIOLIN"))
        self.saxophone_swap_btn.setText(_translate("SwapTool", "SAXOPHONE"))
        self.trombone_swap_btn.setText(_translate("SwapTool", "TROMBONE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SwapTool = QtWidgets.QDialog()
    ui = Ui_SwapTool()
    ui.setupUi(SwapTool)
    SwapTool.show()
    sys.exit(app.exec_())
